# Generated by Django 3.2.5 on 2021-07-30 18:24

from django.db import migrations, models
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210730_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=smartfields.fields.ImageField(upload_to='media'),
        ),
    ]
