# Generated by Django 3.2.5 on 2021-08-03 21:23

from django.db import migrations, models
import smartfields.fields
import smartfields.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_comment_randuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('thumbnail', smartfields.fields.ImageField(upload_to='media')),
            ],
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
